--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cars; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cars (
    "carNumber" integer NOT NULL,
    "invoiceNumber" text NOT NULL,
    "positionInTrain" integer NOT NULL,
    "freightEtsngName" text NOT NULL,
    "freightTotalWeightKg" integer NOT NULL,
    "dateAndTimeLastOperation" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "lastOperationName" text DEFAULT ''::text NOT NULL,
    "lastStationName" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public.cars OWNER TO postgres;

--
-- Name: Car_carNumber_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cars ALTER COLUMN "carNumber" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Car_carNumber_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Trains; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Trains" (
    "trainNumber" integer NOT NULL,
    "fromStationName" text DEFAULT ''::text NOT NULL,
    "toStationName" text DEFAULT ''::text NOT NULL,
    "trainIndexCombined" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Trains" OWNER TO postgres;

--
-- Name: Trains_trainNumber_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Trains" ALTER COLUMN "trainNumber" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Trains_trainNumber_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Email" text NOT NULL,
    "UserName" text,
    "NormalizedUserName" text,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: trainsCars; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."trainsCars" (
    "traintNumber" integer NOT NULL,
    "carNumber" integer NOT NULL
);


ALTER TABLE public."trainsCars" OWNER TO postgres;

--
-- Data for Name: Trains; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Trains" ("trainNumber", "fromStationName", "toStationName", "trainIndexCombined") FROM stdin;
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Email", "UserName", "NormalizedUserName", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20231211095935_Initial	7.0.11
20231211100752_Initial3	7.0.11
20231211145904_Refactoring train	7.0.11
20231220103733_Models update	7.0.11
20231227072454_Db update	7.0.11
\.


--
-- Data for Name: cars; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cars ("carNumber", "invoiceNumber", "positionInTrain", "freightEtsngName", "freightTotalWeightKg", "dateAndTimeLastOperation", "lastOperationName", "lastStationName") FROM stdin;
\.


--
-- Data for Name: trainsCars; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."trainsCars" ("traintNumber", "carNumber") FROM stdin;
\.


--
-- Name: Car_carNumber_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Car_carNumber_seq"', 1, false);


--
-- Name: Trains_trainNumber_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Trains_trainNumber_seq"', 1, false);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, false);


--
-- Name: Trains PK_Trains; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Trains"
    ADD CONSTRAINT "PK_Trains" PRIMARY KEY ("trainNumber");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: cars PK_cars; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT "PK_cars" PRIMARY KEY ("carNumber");


--
-- Name: trainsCars PK_trainsCars; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."trainsCars"
    ADD CONSTRAINT "PK_trainsCars" PRIMARY KEY ("traintNumber", "carNumber");


--
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- PostgreSQL database dump complete
--

